name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Trigger when pushing a version tag (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          source-url: https://nuget.pkg.github.com/YOUR_GITHUB_USERNAME/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the package
        run: dotnet pack --configuration Release --output nupkgs

      - name: Add GitHub Packages Source
        run: dotnet nuget add source --username Aha43 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/YOUR_GITHUB_USERNAME/index.json"
      
      - name: Push package to GitHub Packages
        run: dotnet nuget push nupkgs/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
      