name: Publish to NuGet.org

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # No GitHub Packages needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and pack NuGet package
        run: dotnet pack --configuration Release --output nupkgs --include-symbols --include-source

      - name: Push package to NuGet.org
        run: dotnet nuget push nupkgs/*.nupkg --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }}
